/**
 * Format date to German locale
 */
export function formatDate(dateString: string): string {
	const date = new Date(dateString);
	return new Intl.DateTimeFormat('de-DE', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	}).format(date);
}

/**
 * Truncate text to specified length
 */
export function truncate(text: string, length: number): string {
	if (text.length <= length) return text;
	return text.substring(0, length).trim() + '...';
}

/**
 * Strip HTML tags from string
 */
export function stripHtml(html: string): string {
	return html.replace(/<[^>]*>/g, '');
}

/**
 * Generate slug from text
 */
export function slugify(text: string): string {
	return text
		.toString()
		.toLowerCase()
		.trim()
		.replace(/\s+/g, '-')
		.replace(/[^\w\-]+/g, '')
		.replace(/\-\-+/g, '-');
}

/**
 * Generate avatar URL from UI Avatars API
 */
export function getAvatarUrl(name: string): string {
	const encodedName = encodeURIComponent(name);
	return `https://ui-avatars.com/api/?name=${encodedName}&size=200&background=0ea5e9&color=fff&bold=true`;
}

/**
 * Clean WordPress content - remove "more" links and fix relative URLs
 */
export function cleanWordPressContent(content: string): string {
	if (!content) return '';

	let cleaned = content;

	// Remove <!--more--> tag
	cleaned = cleaned.replace(/<!--more-->/gi, '');

	// Remove "more" span and link generated by WordPress
	cleaned = cleaned.replace(/<span id="more-\d+"><\/span>/gi, '');
	cleaned = cleaned.replace(/<a[^>]*class="more-link"[^>]*>.*?<\/a>/gi, '');

	// Remove any links pointing to subdomain posts
	cleaned = cleaned.replace(
		/<a[^>]*href="https?:\/\/content\.avezgigurcihanaltakan\.com[^"]*"[^>]*>.*?<\/a>/gi,
		''
	);

	// Fix self-closing tags
	cleaned = cleaned.replace(/<(br|hr|img)([^>]*)>/gi, '<$1$2 />');

	return cleaned.trim();
}
